spring:
  datasource:
    url: jdbc:h2:~/test
    driver-class-name: org.h2.Driver
    username: sa
    password: 123456

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: h2
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true

